# Generated by Django 3.0.5 on 2020-05-11 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='pdf',
            new_name='my_file',
        ),
        migrations.RemoveField(
            model_name='book',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='book',
            name='title',
        ),
    ]
