# Generated by Django 3.0.5 on 2020-05-11 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_catalog', '0002_auto_20200511_0851'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
