# Generated by Django 3.0.5 on 2020-05-11 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_catalog', '0005_auto_20200511_0924'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
