# Generated by Django 3.0.5 on 2020-05-11 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_catalog', '0011_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
