# Generated by Django 3.0.5 on 2020-05-11 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_catalog', '0013_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
